### PR TITLE
WIP: fui integration

### PR DESCRIPTION
**Pull request by xliiv**

### CODE REVIEW

**Comment by timvisee** [comment]
Although I like what `fui` would provide based on what I've seen from it, wouldn't implementing it be quite a lot of work? Or is it possible to use the `clap::App` definition for showing the `fui` interface?

Note that if implementing is an easy task, and something people are interested in, I'd prefer to have it behind a flag, sub-command or other toggle.

**Comment by xliiv** [comment]
Sorry, i made a mistake.
I meant to create a merge request in my fork of `ffsend`, since it's an experiemnt and more steps needs to be done before/if ever i propose you a integration.
Closing it.

**Comment by xliiv** [comment]
And answering to your doubts :)
In this shape it should be 100% backward compatible except running `ffsend` with no params like this
```
$ ffsend
```
will open tui, rest of stuff should work like before.

**Comment by xliiv** [comment]
Btw, i can afford to paste a gif instead of talking.

image


But like a said it's early stage and need more work.

**Pull request closed without merging**
