### PR TITLE
Added zsh completion

### PR DESCRIPTION
**Pull request by ogarcia**
This PR adds support for zsh completion. Simply copy it to `/usr/share/zsh/site-functions/_ffsend` to see the <kbd>TAB</kbd> magic. It can be added into packages :wink:

### CODE REVIEW

**Comment by timvisee** [comment]
Awesome, thanks!

By the way, because the project is using [`clap`](https://clap.rs) for command-line argument handling, it is possible to generate completions for common shells at compile time. I'll probably switch to that method in the future.

I'll merge your PR manually through GitLab in a minute.

**Comment by timvisee** [comment]
I've just added automatically generated completion files for common shells to the [`./contrib/completions/`](https://github.com/timvisee/ffsend/tree/master/contrib/completions) directory in fba888c5aa841db303ef8b18904a89fed521ff9d.

@ogarcia Could you possibly verify the `zsh` completion file is still as functional? I might revert to your version if it isn't.

**Comment by ogarcia** [comment]
@timvisee for me don't work these completions, neither the arguments nor the subcommands. Seems some is broken, but I don't see where is the error.

**Comment by timvisee** [comment]
Thank you for giving it a try. Will probably revert for now.

**Pull request merged**
